name: RtProviderMode
description: RtProvider using mode example
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactter: ^8.0.0-dev

flutter:
  uses-material-design: true
