name: reactter
description: A light, powerful and quick Reactive State Management, Dependency Injection and Event Handler.
homepage: https://2devs-team.github.io/reactter/
documentation: https://2devs-team.github.io/reactter/
repository: https://github.com/2devs-team/reactter/tree/master/packages/reactter
license: MIT License
version: 8.0.0-dev.17

topics:
  - reactive
  - state
  - dependency
  - event

screenshots:
  - description: "Reactter DevTools Extension"
    path: doc/screenshots/devtools.png
  - description: "Reactter Example App"
    path: doc/screenshots/example_app.png


environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^2.0.1
  test: ^1.24.0
  flutter_test:
    sdk: flutter

scripts:
  test: "flutter test --coverage"
  analyze: "dart analyze ."
  public-dry-run: "dart pub publish --dry-run"
  public: "dart pub publish"