name: reactter
description: Reactter is a light, powerful and reactive state management.
version: 4.1.2
homepage: https://2devs.io
license: MIT License
repository: https://github.com/2devs-team/reactter

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.4
