name: reactter
description: A light, powerful and quick Reactive State Management, Dependency Injection and Event Management.
version: 7.0.0-pre.2
license: MIT License
repository: https://github.com/2devs-team/reactter/tree/master/packages/reactter

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  flutter_reactter:
    path: ../flutter_reactter
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.1
  lints: ^2.0.1
