name: reactter
description: A light, powerful and quick Reactive State Management, Dependency Injection and Event Handler.
homepage: https://2devs-team.github.io/reactter/
documentation: https://2devs-team.github.io/reactter/
repository: https://github.com/2devs-team/reactter/tree/master/packages/reactter
license: MIT License
version: 8.0.0-dev.5

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^5.1.1
  test: ^1.25.2
  flutter_test:
    sdk: flutter

scripts:
  test: "flutter test --coverage"
  analyze: "dart analyze ."
  public-dry-run: "dart pub publish --dry-run"
  public: "dart pub publish"