name: examples
description: Reactter examples
version: 3.0.0+1
publish_to: "none"

environment:
  sdk: ">3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  url_launcher: ^6.1.2
  intl: ^0.17.0
  flutter_reactter: ^8.0.0-dev.5
  #  path: ../

dev_dependencies:
  custom_lint: ^0.5.11
  flutter_lints: ^2.0.2
  reactter_lint:
    path: ../../reactter_lint

flutter:
  uses-material-design: true
