name: reactter
description: A light and powerful state management like React syntax.
  Reduce significantly boilerplate code.
  Improve code readability.
  Unidirectional data flow.
  An easy way to share global information in the application.
  Control re-render widget tree.
version: 2.0.0-dev.1
homepage: https://2devs.io
license: MIT License
repository: https://github.com/Leoocast/reactter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
