name: reactter
description: Reactter is a package that uses [Get](https://pub.dev/packages/get) as base to implement reactive behavior using some names and functionality we are familiarized from React Js.
version: 0.0.1-dev.1
homepage: https://2devs.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
