name: reactter
description: A light state management with React syntax. Reduce boilerplate code
  and improve code readability.
version: 2.0.0-dev.1
homepage: https://2devs.io
license: MIT License
repository: https://github.com/Leoocast/reactter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  test: any

flutter: null
