name: reactter
description: Use Get as React.
version: 0.0.1-dev.1
authors:
  - Creator Leo Castellanos <leoocast.dev@gmail.com>
  - Creator Carlos León <carleon.dev@gmail.com>
homepage: 2devs.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
