name: reactter_lint
description: Reactter_lint is an analytics tool for Reactter that helps developers to encourage good coding practices and preventing frequent problems.
version: 0.1.0
homepage: https://2devs.io
license: MIT License
repository: https://github.com/2devs-team/reactter

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  analyzer: ^5.12.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.0
