name: flutter_reactter
description: A light, powerful and quick Reactive State Management, Dependency Injection and Event Handler.
homepage: https://2devs-team.github.io/reactter/
documentation: https://2devs-team.github.io/reactter/
repository: https://github.com/2devs-team/reactter/tree/master/packages/flutter_reactter
license: MIT License
version: 8.0.0-dev.15

topics:
  - reactive
  - state
  - dependency
  - event

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  reactter: ^8.0.0-dev.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

scripts:
  test: "flutter test --coverage"
  analyze: "dart analyze ."
  public-dry-run: "dart pub publish --dry-run"
  public: "dart pub publish"