name: flutter_reactter
description: A light, powerful and quick Reactive State Management, Dependency Injection and Event Management.
version: 5.0.1
homepage: https://2devs.io
license: MIT License
repository: https://github.com/2devs-team/reactter

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  reactter: ^5.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
