name: LifecycleEventHandler
description: Lifecycle event handler example
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactter: ^8.0.0-dev.20

flutter:
  uses-material-design: true
