name: Counter
description: A event handler example
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactter: ^7.2.0

flutter:
  uses-material-design: true
