# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_reactter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/reactter

    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install app dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: reactter-coverage
          path: ./packages/reactter/coverage/lcov.info
          
  build_flutter_reactter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/flutter_reactter

    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: "stable"
      - name: Install app dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: flutter_reactter-coverage
          path: ./packages/flutter_reactter/coverage/lcov.info
          
  upload-to-codecov:
    needs: [build_reactter, build_flutter_reactter]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
